### ISSUE TITLE
Container IP changes break the cluster

### ISSUE THREAD

**Issue by pwfff** [Grokzen/docker-redis-cluster#10]
I'm not sure why my container changed IPs and maybe that's my real issue, but if you could run `redis-cli -p 7000 cluster meet 127.0.0.1 700X` for each of the nodes at the end of the Dockerfile then I think this problem would go away. That's what I did to fix it once it was up. It would be nice if it was that way by default.
```
243:S 19 May 19:11:07.279 * Connecting to MASTER 172.17.0.7:7000
243:S 19 May 19:11:07.279 * MASTER <-> SLAVE sync started
243:S 19 May 19:11:07.279 # Error condition on socket for SYNC: Connection refused
root@0cd0e6c5d29f:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:08
          inet addr:172.17.0.8  Bcast:0.0.0.0  Mask:255.255.0.0
```

**Comment by seubert** [comment]
This is an issue for me as well.

**Comment by Grokzen** [comment]
Yeah, i do not think i will change this behaviour back to use `127.0.0.1` addresses again. One of the reasons that i changed to use the external IP address of the docker container was that if i use 127.0.0.1 as the IP i want to join up the cluster nodes, they will track 127.0.0.1 in the command `CLUSTER NODES` that is used to detect the current state of the cluster. And if the redis cluster thinks that all nodes is on localhost only, that will eliminate anyone from accessing the clsuter from anywhere but from localhost. Only clients running on the local machine will be able to resolve 127.0.0.1:7000 correctly. This is also not really a problem for just the docker solution, if you have a real cluster and the IP changes for one of the nodes, then you are probably out of luck anyway because i do not think that redis itself detects IP changes and updates the cluster.

The one solution that i can figure out right now to get around of this problem in any case is that in your clients you should specify all nodes in your cluster manually and avoid doing cluster detection with `CLUSTER NODES`. Then you should be able to specify DNS names instead of IP addresses and let the client figure out where your nodes are. The absolute best way would be for redis itself to sor this out with some new internal mechanism.
