### ISSUE TITLE
The image cannot start on platforms (kubernates for example) which do not accept ROOT as the running user

### ISSUE THREAD

**Issue by avillev** [Grokzen/docker-redis-cluster#102]
I work in a company where the Kubernates platform does not accept ROOT as a container image. I hear that this is a pretty comon rule to apply.

Could we consider to allow that image to function without being ROOT ?

**Comment by Grokzen** [comment]
@avillev This container is not designed for either kubernetes or being run as non-root really. I have no plans to change either things myself, but if you want to submit a PR with some proposed changes you are welcome to do so.

**Comment by maneeshbhunwal123** [comment]
@Grokzen Do you know what will it take to get this done?
I can contribute on this

**Comment by Grokzen** [comment]
@maneeshbhunwal123 I have no plans on accepting any change that will go in that direction so do not bother with it. If you need a redis cluster in things like kubernetes then you will need to look elsewhere or simply spin up your own redis nodes and manually setup the cluster because it is much easier then trying to adapt this repo to work with it. My goal with this repo has been what is stated in the README.md file and not much more. Simplicity is my goal and not support for all possible solutions.
