### ISSUE TITLE
Old docker hub tags missing over night?

### ISSUE THREAD

**Issue by puittenbroek** [Grokzen/docker-redis-cluster#120]
Hi,

We've been using `grokzen/redis-cluster:3.2.12` for a while now, works like a charm.
But overnight, these old tags went missing. Breaking our local development and CI environments.

Was this intentional or not?

**Comment by Grokzen** [comment]
Hi @puittenbroek . Yes sorry for the inconvenience of doing that but i announced a while back in #111 that i would be removing them at some point and move more towards just hosting the redis-server versions that is in their major version support policy.

The major reason for doing this from my part is that docker.hub is limiting the number of pulls that you can do within a given timestamp so i simply reduced the number of available images to reduce this number down a bit so people can still pull home the later releases w/o issues.

I will also in the future look into hosting all tags again here on the github docker index instead as it should have no issues hosting and pulling down many different tags and number of pulls.

So to mitigate this issue for you, i have two solutions.

1. Implement a local docker image cache so that you only have to download the image once and you can cache it locally for both faster download but you will not consume more downloads from docker.hub then you need.
2. Start building the older versions locally because that support has not been removed from the repo and will not be removed any time soon.  You can build the version you desire with either invoke `invoke build 3.2.12` for example. Or you can build it with plain docker if you first clone the git repo you can run `docker build --build-arg redis_version=3.2.12 -t grokzen/redis-cluster:3.2.12 .` and either store them locally or just build them at each CI build step.

I really recommend that you implement a local docker image cache solution, that is what i myself had to do to even use my own images so you are not alone in suffering from the docker.hub limitations :)
