### ISSUE TITLE
Delete redis data after make down

### ISSUE THREAD

**Issue by mehdi-fathi** [Grokzen/docker-redis-cluster#130]
Hi, 

thanks for this repo. I have a problem with it.  I run makeup and insert my data in cluster Redis DB but when run make down and run make up command all data has been deleted!. How can I prevent delete data? I have searched about it may be it has been related to appendonly param but appendonly is 'yes'.

**Comment by Grokzen** [comment]
@mehdi-fathi I am not fully sure where it is written, but i think it should say somewhere that this is only for local dev/debugging/demo etc, but this image is not really intended to work like what you want it to work. Due to how we build and start the container and all nodes inside it, there is no real way for the nodes to understand that it should start fresh or that it should continue from a existing state. You can always attempt to volume map up the data folder and see if you can get it to work yourself, but the stuff it not really designed for this and i have no plans on supporting both solutions as running it in that mode is not something that i see for this image.
