### ISSUE TITLE
compatibility with Swarm

### ISSUE THREAD

**Issue by mrmunch** [Grokzen/docker-redis-cluster#14]
As I understand, this image will run a single container which contains 6 redis instances? So I have 6 instances on one machine? What's the benefit of that?
Or can I use this for Docker Swarm mode - so that I have 6 VMs configured in Docker Swarm mode and run this image over these 6 VMs?

**Comment by Grokzen** [comment]
The target/intended purpose of this image is to run it when developing a redis-cluster client. When doing that there is no need to run multiple containers just because to make it compatible with tools like swarm and kubernetes for example.

As is i will not make any effort to make this image compatible with swarm or any other tool then docker-compose and that one is used to make it simpler with image names, port openings and start/stopping of containers.

If you want to put in the effort to refactor this repo into one that is compatible with swarm but where swarm is not required i will accept that kind of work, but i myself will not put in the effort because i do not have the need for it.

On a comment to make it compatible with swarm. Currently the container just starts a supervisord process that starts 6 redis-servers in one container. It should be fairly simple to change that part to only run one redis-server and then let swarm start 6 seperate containers and let swarm do the heavy lifting when dealing with the cluster setup and service discovery.

**Comment by Grokzen** [comment]
@mrmunch Closing this issue as docker swarm support is not in the scope of this project. This docker image is built to run locally on your machine to help development of redis cluster clients and not much more. If you want to fork it and make changes so it will work better for your scenario of docker swarm, i would approve of that very much.
