### ISSUE TITLE
Images before < 6.x have been dropped from registry

### ISSUE THREAD

**Issue by ostrolucky** [Grokzen/docker-redis-cluster#148]
[symfony is using 5.0.4 image](https://github.com/symfony/symfony/blob/4.4/.github/workflows/integration-tests.yml#L45) but now it [stopped working](https://github.com/ostrolucky/symfony/actions/runs/3725337427/jobs/6318080448#step:3:139). On https://hub.docker.com/r/grokzen/redis-cluster/tags I can't see anything older than 6.x, even though description clearly references even 3.x versions.

I tried updating GH action to newest image, but this [fails the tests](https://github.com/ostrolucky/symfony/actions/runs/3725349903/jobs/6318102268#step:9:3414) and looks like it would need some work to fix it

**Comment by Grokzen** [comment]
It is clearly stated in the README what the major redis version support will be moving forward since early 2020 and it just took me some time until now to get to include and release 7.0 version and drop 5.0 line.

https://github.com/Grokzen/docker-redis-cluster#redis-major-version-support-and-dockerhub-availability

The main argument for this when i implemented it was to reduce the maintainer need for me to build and publish all possible versions forever.

The second argument is to help push the redis users community forward to adopt and install newer versions. Note tho that the repo will still maintain and be able to build all redis cluster versions all the way back to 3.0 so it should always be possible to clone the repo, build the image and either self host a version that you need for your cause, or to do a fork/publish either here on github docker repo or docker hub.

A third argument was that at least at the time i added this policy was that docker hub was limiting downloads of tags to a certain number within a given timeframe and it would cause issues having to many tags published as it would eat up my download count fast. Dockerhub themself pushed the entire community to adopt the strategy of self hosting your own docker image mirrors for instance locally on-site within a company or on separate service or plan that allowed for more downloads per hour.

My recommendation is that you clone this repo and run something like `docker build --build-arg redis_version=5.0.4 -t grokzen/redis-cluster .` to build your own image and run that one locally. Or if you build it locally and self publish it somewhere and point to that in your integration scripts.

What i can do however is to investigate what dockerhub has done since 2020 regarding image downloads on free plans and what the limitations and restrictions is right now to see if that might change my policy back to what it used to be. But, i would say that my argument regarding only supporting and publishing last 3 major versions might still superseed that in the end, we will see.
