### ISSUE TITLE
Latest update has caused broken connection 

### ISSUE THREAD

**Issue by lreher** [Grokzen/docker-redis-cluster#154]
Hello, ever since the latest updates to these images our redis cluster has started refusing to connect. Has there been any changes to how we configure this?

**Comment by Sedemicra** [comment]
Same issue here. Connecting applications complain about "Redis is running in protected mode". This was not an issue before the updates (was using "latest" tag). Now, since all the images available in docker hub are updated, there isn't an option to go back to a previously working version either.

**Comment by Grokzen** [comment]
@lreher @Sedemicra `grokzen/redis-cluster:latest` tag was updated yesterday from 6.2 to 7.0 and in that build the default is protected mode see #153 for it. You will have to disable protected mode manually in 7.0 and above before running the cluster.

**Comment by Sedemicra** [comment]
Well aware of the risks of `:latest`, just taking over someone elses project :) 
Just before my previous comment I didn't see the 6.2.x tags in docker hub so I figured they were no longer an option, but now they are available again - not sure what happened there. But thanks for making me look again @Grokzen 
Might consider trying some option from #149 in the future, but currently 6.2.x tag will work just fine.

**Comment by Grokzen** [comment]
All tags for 6.0, 6.2 & 7.0 should have been there since the last year at least O.o i hope so at least, most of the time i don't keep up with minor versions as they release. I have been thinking about some other solutions for that, maybe make a cron based solution with a github action that constantly builds all released versions for example, but that solution is not ready yet.

On the config side i have also been messing around with a new configuration solution that uses and makes environment variables much more usefull and able to configure anything instead of having to implement and support each key and variable as they are needed. The simplest way is to just volume map in your own configuration files to make it what you want, but i think that environment variables is the way to really go in the long run as things is going towards env vars more.

**Comment by lreher** [comment]
Thanks for the follow up, we've just replaced the image with an older digest.

**Comment by lreher** [comment]
I saw the same behaviour as @Sedemicra, all the tags look like they were replaced yesterday?

**Comment by Sedemicra** [comment]
It seems there is a bug in docker hub [tags](https://hub.docker.com/r/grokzen/redis-cluster/tags) page logic. 
When I open (or refresh) it I only see "latest" and 7.0.x tags on first page, and on next page there are only 6.0.x tags. I only see 6.2.x tags when I navigate back to first page and then they miraculously appear. This is why I originally missed them. 
It seems to be some kind of general issue in docker hub as I see similar problem on other projects.

**Comment by Grokzen** [comment]
@Sedemicra I think it is based on what order i upload the latest layers in, best is to sort them Z-A then it would always come in the correct order
