### ISSUE TITLE
Timeout on redirect to slot

### ISSUE THREAD

**Issue by cosminci** [Grokzen/docker-redis-cluster#16]
Running the commands in the README does not seem to yield a reachable cluster. I've tried the 
```
docker run -i -t -p 7000:7000 -p 7001:7001 -p 7002:7002 -p 7003:7003 -p 7004:7004 -p 7005:7005 -p 7006:7006 -p 7007:7007
``` 
with
- grokzen/redis-cluster
- grokzen/redis-cluster:3.0.7
- newly built image from the master branch

The result is always the same when connecting via redis-cli from the same machine running the container (which is localhost): 
```
redis-cli -c -p 7000
127.0.0.1:7000> set a b
-> Redirected to slot [15495] located at 172.17.0.3:7002
Could not connect to Redis at 172.17.0.3:7002: Operation timed out
Could not connect to Redis at 172.17.0.3:7002: Operation timed out
(150.98s)
```

All commands seem to work properly from the docker container:
```
docker exec -it 1c4dbc9e5185 /bin/bash
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
root@1c4dbc9e5185:/data# redis-cli -c -p 7000
127.0.0.1:7000> set a b
-> Redirected to slot [15495] located at 172.17.0.3:7002
OK
172.17.0.3:7002>
```

Jedis fails to connect to the cluster at all: 
```
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
Caused by: java.net.SocketTimeoutException: connect timed out
Caused by: java.net.SocketTimeoutException: connect timed out
```

Seems to me I may be missing something obvious, but can't figure out what. Running MAC OS X, Docker 17.03.0-ce-mac1.

P.S.: same result when building & starting using docker compose.
P.P.S.: hardcoding the IP in the entrypoint to 127.0.0.1 is a workaround.

**Comment by Grokzen** [comment]
If you modify this line https://github.com/Grokzen/docker-redis-cluster/blob/master/docker-data/docker-entrypoint.sh#L24 to `IP='127.0.0.1'` rebuild and try again it should start to work.

The problem is that you are running on a mac and how they deal with network. Becuase you basially run docker ina virtualbox and they have still not fixed so that the internal doccker network is exposed from inside the doker container, to you vm then to you mac so that your mac can connect to the 172.17... network it will allways be broken.

To confirm this is the case you can issue the command `CLUSTER SLOTS` to your cluster from inside the container and it should say it mapes to all 172.17... ip addresses.
