### ISSUE TITLE
redis cluster connection timeout or refuse connection

### ISSUE THREAD

**Issue by godpit** [Grokzen/docker-redis-cluster#67]
A another server with application would access the redis cluster within docker server. 

It is connect timeout without the ENV of IP.

It is refuse connection with the ENV of IP = 0.0.0.0.

It is connect timeout with the ENV of IP = Intranet IP （such as : 127.17.0.2).

The docker server with application would access the redis cluster within docker server. 
However, it work well.

How to solve it?

**Comment by godpit** [comment]
Such as A another server IP : 192.168.1.10, the docker server IP : 192.168.1.11.
It is ok by telneting 192.168.1.11 7000 ~7005, but the application(192.168.1.10) accessed the redis cluster with 192.168.1.11:7000. It just connect timeout or refuse connetion

**Comment by godpit** [comment]
redis-cli -h 192.168.1.10 -p 7000, it is still ok.

**Comment by godpit** [comment]
The os is centos7.

**Comment by godpit** [comment]
docker run -e  IP=0.0.0.0  -d -p 7000:7000 -p 7001:7001 -p 7002:7002 -p 7003:7003 -p 7004:7004 -p 7005:7005 -p 7006:7006 -p 7007:7007 grokzen/redis-cluster

**Comment by Grokzen** [comment]
@godpit Can you print the output of `CLUSTER INFO` and  `CLUSTER SLOTS` ?

Usually this container i not intended to be accessed from outside the machine that is running the container. This is a usual problem but not a problem that i really care about solving.

**Comment by godpit** [comment]
![img_0741](https://user-images.githubusercontent.com/34534331/53149142-d80da080-35e7-11e9-8905-9f101c14f7a0.JPG)
![img_0740](https://user-images.githubusercontent.com/34534331/53149143-d8a63700-35e7-11e9-814a-b9f226598ea5.JPG)
This is a very common scenario that should be supported.

**Comment by Grokzen** [comment]
It is stated in the README about the purpose and intent and the limitations of this container and what features it support. I have said before that i will not put in the effort to this container to make it work in any further ways then from the local machine. If you have that use-case please feel free to fork the repo, do the changes that you need to make it work for your case, and if you really want, contribute the changes back here that would extend the current functionality but keep the simple ease of use that it currently has. Production quality redis containers is out there that you can use and build a redis cluster that will work for your use-case and your requirements. This containers main purpose is to have something that you can very easily and quickly spin up to get a cluster that you can reach from your won machine to either demo redis cluster, run redis-cli and test out commands, develop code against, run in CI envrionments.

But the basic problem you are having from the screenshots is that your redis cluster nodes have tracked the internal docker IP address of what you have on the inside of the container. So when a client connects to your cluster then it will use and track these ip addresses and try to connect to each node with 172.18.0.2 for example. So that works when you are on the same machine, or if you have "fixed" your network to have that resolvable from another host. That is outside the scope of my container to solve.
